[[maps]]
source = "res://data/maps/overworld.map"
tile_size = 48.0

[[entities]]
name = "World"
prefab = "res://prefabs/world_controller.prefab.toml"

[entities.tags]
values = ["system"]

[[entities]]
name = "Player"
prefab = "res://prefabs/player.prefab.toml"

[entities.transform]
x = 96.0
y = 96.0

[entities.tags]
values = ["player"]

[entities.data]
character = "res://data/characters/player.toml"

[[entities]]
name = "Merchant"
prefab = "res://prefabs/npc.prefab.toml"

[entities.transform]
x = 720.0
y = 288.0

[entities.sprite]
sort_order = 12

[entities.tags]
values = ["npc", "character"]

[entities.data]
character = "res://data/characters/merchant.toml"

[[entities]]
name = "Goblin"
prefab = "res://prefabs/goblin.prefab.toml"

[entities.transform]
x = 816.0
y = 96.0

[entities.sprite]
sort_order = 14

[entities.tags]
values = ["npc", "character"]

[entities.data]
character = "res://data/characters/goblin.toml"
