[components]
name = { value = "goblin_prefab" }

[components.sprite]
texture = "asset://sprites/player.png"
width = 80.0
height = 80.0

[components.controller]
type = "WandererController"
speed = 55.0
